"""
.. module:: main.py
   :platform: Unix, Windows
   :synopsis: Autogenerated file from fbs library, entry-point of the PLATFORM6573_v1 .
.. moduleauthor:: Seokhun Jeon <seokhun.jeon@keti.re.kr>
"""

from fbs_runtime.application_context import ApplicationContext
from ui_setup import form

import sys


class AppContext(ApplicationContext):           # 1. Subclass ApplicationContext
    def run(self):                              # 2. Implement run()
        window = form()
        version = self.build_settings['version']
        #window.setWindowTitle("MDSP_AI v" + version)
        #window.resize(500, 750)
        window.show()
        return self.app.exec_()                 # 3. End run() with this line

if __name__ == '__main__':
    appctxt = AppContext()                      # 4. Instantiate the subclass
    exit_code = appctxt.run()                   # 5. Invoke run()
    sys.exit(exit_code)

